export enum ScreenNames {
  login = 'login',
  register = 'register',
  dashboard = 'dashboard',
  requests = 'requests',
  profile = 'profile',
  groups = 'groups',
  chat = 'chat',
  loading = 'loading',
  chats = 'chats',
  search = 'search',
  imageView = 'imageView',
  information = 'information',
  editprofile = 'editprofile',
}
